#--------------------------------------#
# Don't change this plz (it will break...)
client_id = "2210535565.11339190985360"
#--------------------------------------#

# Fill values by uncommenting the field ID line under each label.
# WARNING: An empty string WILL literally set that field to empty (i.e. clear it), comment out field you don't want to be automatically updated


# Docs: https://docs.slack.dev/reference/methods/users.profile.set#profile-fields

# title = 
# phone = 
# real_name =
# display_name = 

# Docs: https://docs.slack.dev/reference/methods/users.profile.set#status

# status_text = 
# status_emoji =

# ONLY SET TO INT (See docs)
# status_expiration =

# status_clear_on_focus_end =



# Hackclub Slack specific

# Github URL
# Xf09V176UVK5 =

# Birthday (YYYY-MM-DD)
# Xf0A06G5MKJM =

# Dog or Cat or Infrastructure?
# Xf09VB64B1PE =

# PFP Credit
# Xf09V5HE0MU6 =

# Website
# Xf09V45UG8AZ =

# Fav Languages/Tools
# Xf09V1775W91 =

# Start Date (YYYY-MM-DD)
# Xf09UWTTJF6Z =

# Fandoms
# Xf0AC8RUMQCT =

# Favorite Emoji
# Xf0APVLWEUC8 =

# HAM Callsign
# Xf0A06G5TTKK =

# Check README.md
